ApiService:
  Db:
    DataConnString:
      settings-key: Ethereum-DataConnString
      types:
        - AzureTableStorage
    LogsConnString:
      settings-key: LogsConnString
      types:
        - AzureTableStorage
  MinimalTransactionAmount:
    settings-key: Ethereum-MinimalTransactionAmount
  ParityNodeUrl:
    settings-key: Ethereum-ParityNodeUrl 
SignApiService:
  Db:
    LogsConnString:
      settings-key: LogsConnString
      types:
        - AzureTableStorage
MonitoringServiceClient:
    MonitoringServiceUrl:
        settings-key: MonitoringServiceUrl
SlackNotifications: 
    AzureQueue:
        ConnectionString:
            settings-key: SlackNotificationsConnString
            types:
              - AzureTableStorage
        QueueName: 
            settings-key: SlackNotificationsQueueName
    ThrottlingLimitSeconds: 
        settings-key: SlackNotificationsThrottlingLimit